### ISSUE TITLE
New version is crashing

### ISSUE THREAD

**Issue by RandelP** [izinin/radio_amoris#12]
osVersion: google/husky/husky:14/AP2A.240905.003/2024091900:user/release-keys
package: com.zindolla.radioamoris:20
process: com.zindolla.radioamoris
processUptime: 217 + 447 ms
installer: com.android.vending

java.lang.RuntimeException: Unable to start service com.zindolla.radioamoris.MyRadioService@497377c with Intent { act=audio.start cmp=com.zindolla.radioamoris/.MyRadioService (has extras) }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{c2432f8 16302:com.zindolla.radioamoris/u0a153} targetSDK=34
      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5126)
      at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2439)
      at android.os.Handler.dispatchMessage(Handler.java:107)
      at android.os.Looper.loopOnce(Looper.java:232)
      at android.os.Looper.loop(Looper.java:317)
      at android.app.ActivityThread.main(ActivityThread.java:8623)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
      at com.android.internal.os.ExecInit.main(ExecInit.java:50)
      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{c2432f8 16302:com.zindolla.radioamoris/u0a153} targetSDK=34
      at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
      at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
      at android.os.Parcel.readParcelableInternal(Parcel.java:5036)
      at android.os.Parcel.readParcelable(Parcel.java:5018)
      at android.os.Parcel.createExceptionOrNull(Parcel.java:3187)
      at android.os.Parcel.createException(Parcel.java:3176)
      at android.os.Parcel.readException(Parcel.java:3152)
      at android.os.Parcel.readException(Parcel.java:3094)
      at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6998)
      at android.app.Service.startForeground(Service.java:778)
      at com.zindolla.radioamoris.MyRadioService.b(Unknown Source:187)
      at com.zindolla.radioamoris.MyRadioService.f(Unknown Source:92)
      at com.zindolla.radioamoris.MyRadioService.onStartCommand(Unknown Source:0)
      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5108)

**Comment by RandelP** [comment]
The problem has been solved after the latest update. Thank you very much for the quick action!
